const ADD = 'ADD';
const REMOVE = 'REMOVE';
const PRODUCT_QUANTITY ='PRODUCT_QUANTITY';
const GET_TOTAL = 'GET_TOTAL'; 
const RESET = 'RESET';
const GET_AMOUNT = 'GET_AMOUNT';

export {ADD,REMOVE,PRODUCT_QUANTITY,GET_TOTAL,RESET,GET_AMOUNT};